s = sorted([36,5,-12,9,-21])
print(s)
s1 = sorted([36,5,-12,9,-21],key=abs)
print(s1)
s3 = sorted(['bob','about','Zoo','Credit'])
print(s3)
s4 = sorted(['bob','about','Zoo','Credit'],key=str.lower)
print(s4)
s5 = sorted(['bob','about','Zoo','Credit'],key=str.lower,reverse=True)
print(s5)